language: scala
scala:
- 2.11.7

jdk:
  - oraclejdk8

before_script:
  - "sbt ++$TRAVIS_SCALA_VERSION scalafmtTest test:scalafmtTest"

script: "sbt ++$TRAVIS_SCALA_VERSION -J-Dsun.net.maxDatagramSockets=2048 clean coverage test"
after_success: "sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls"