language: scala
scala:
- 2.11.11
- 2.12.2

jdk:
  - oraclejdk8

before_script:
  - "sbt ++$TRAVIS_SCALA_VERSION scalafmtTest"

script: "sbt ++$TRAVIS_SCALA_VERSION -J-Dsun.net.maxDatagramSockets=2048 clean coverage test"
after_success: "sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls"