version: 2.1

commands:
  credentials:
    description: "Fetch temporary credentials if needed"
    steps:
      - run:
          name: Retrieve temporary Algolia credentials if needed
          command: |
            if [ -z "BINTRAY_USER" ]; then
              curl -s https://algoliasearch-client-keygen.herokuapp.com | sh >> $BASH_ENV
            fi
  test:
    description: "Run the test for Scala << parameters.scala_version >>"
    parameters:
      scala_version:
        type: string
    steps:
      - run:
          name: Run tests for Scala << parameters.scala_version >>
          command: |
            if [ -z "BINTRAY_USER" ]; then
              cat /dev/null | sbt -J-Dsun.net.maxDatagramSockets=2048 '++ << parameters.scala_version >> testOnly -- -l SkipInCI'
            else
              cat /dev/null | sbt -J-Dsun.net.maxDatagramSockets=2048 '++ << parameters.scala_version >> test'
            fi


jobs:
  format:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
            key: sbt-cache-2-13
      - run:
          name: Check formatting
          command: cat /dev/null | sbt '++ 2.13.1 scalafmtCheckAll'
  test-2-11:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache-2-11
      - credentials
      - test:
          scala_version: "2.11.12"
      - save_cache:
          key: sbt-cache-2-11
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  test-2-12:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache-2-12
      - credentials
      - test:
          scala_version: "2.12.10"
      - save_cache:
          key: sbt-cache-2-12
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  test-2-13:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache-2-13
      - credentials
      - test:
          scala_version: "2.13.1"
      - save_cache:
          key: sbt-cache-2-13
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

  release:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Release new version
          command: |
            if [ -z "BINTRAY_USER" ]; then echo "BINTRAY_USER is not set";  exit 1; fi
            if [ -z "BINTRAY_PASS" ]; then echo "BINTRAY_PASS is not set";  exit 1; fi
            cat /dev/null | sbt '+publish'

workflows:
  version: 2
  build:
    jobs:
      - format
      - test-2-11
      - test-2-12:
          requires:
            - test-2-11
      - test-2-13:
          requires:
            - test-2-12
      - release:
          requires:
            - format
            - test-2-11
            - test-2-12
            - test-2-13
          filters:
            branches:
              only: master
            tags:
              only: /^[1-9]+.[0-9]+.[0-9]+.*/
